name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/location.png
    - assets/page-1/images/account.png
    - assets/page-1/images/location-w1s.png
    - assets/page-1/images/account-Cfs.png
    - assets/page-1/images/ellipse-5.png
    - assets/page-1/images/rectangle-14.png
    - assets/page-1/images/account-CHo.png
    - assets/page-1/images/group-1.png
    - assets/page-1/images/location-nty.png
    - assets/page-1/images/line.png
    - assets/page-1/images/icon.png
    - assets/page-1/images/line-bnh.png
    - assets/page-1/images/images-8.png
    - assets/page-1/images/location-XxV.png
    - assets/page-1/images/ellipse-5-KMB.png
    - assets/page-1/images/images-9.png
    - assets/page-1/images/ellipse-7.png
    - assets/page-1/images/home.png
    - assets/page-1/images/free-icon-font-home-3917033-3.png
    - assets/page-1/images/group-2.png
    - assets/page-1/images/group-2-gMP.png
    - assets/page-1/images/free-icon-font-home-3917033-2.png
    - assets/page-1/images/images-10.png
    - assets/page-1/images/free-icon-font-home-3917033-2-KTP.png
    - assets/page-1/images/image-14.png
    - assets/page-1/images/images-10-AGH.png
    - assets/page-1/images/ellipse-6.png
    - assets/page-1/images/free-icon-font-user-3917546-2.png
    - assets/page-1/images/free-icon-font-home-3917033-4-MNZ.png
    - assets/page-1/images/free-icon-font-user-3917546-4.png
    - assets/page-1/images/free-icon-font-user-3917546-2-N7s.png
    - assets/page-1/images/free-icon-font-user-3917546-3.png
    - assets/page-1/images/free-icon-font-user-3917546-4-u77.png
    - assets/page-1/images/ellipse-5-7Wh.png
    - assets/page-1/images/group-2-xvd.png
    - assets/page-1/images/free-icon-font-home-3917033-4.png
    - assets/page-1/images/account-jXP.png
    - assets/page-1/images/home-xe5.png
    - assets/page-1/images/home-3XX.png
    - assets/page-1/images/frame-1.png
    - assets/page-1/images/home-AA5.png
    - assets/page-1/images/location-LY9.png
    - assets/page-1/images/free-icon-font-home-3917033-4-2aV.png
    - assets/page-1/images/group-1-CvD.png
    - assets/page-1/images/home-8Vf.png
    - assets/page-1/images/location-oXo.png
    - assets/page-1/images/home-Pn9.png
    - assets/page-1/images/image-10.png
    - assets/page-1/images/auto-group-hu8v.png
    - assets/page-1/images/ellipse-6-C9f.png
    - assets/page-1/images/home-zt9.png
    - assets/page-1/images/ellipse-7-c6D.png
    - assets/page-1/images/account-cF3.png
    - assets/page-1/images/free-icon-font-user-3917546-4-Rtd.png
    - assets/page-1/images/images-10-9KP.png
    - assets/page-1/images/account-yDs.png
    - assets/page-1/images/account-4ZP.png
    - assets/page-1/images/image-14-SaM.png
    - assets/page-1/images/image-10-CtH.png
    - assets/page-1/images/free-icon-font-sign-out-alt-1.png
    - assets/page-1/images/location-2wB.png
    - assets/page-1/images/free-icon-font-sign-out-alt-1-BZB.png
    - assets/page-1/images/image-11.png
    - assets/page-1/images/border.png
    - assets/page-1/images/location-49w.png
    - assets/page-1/images/space.png
    - assets/page-1/images/auto-group-k5ez.png
    - assets/page-1/images/return.png
    - assets/page-1/images/location-TTP.png
    - assets/page-1/images/backspace.png
    - assets/page-1/images/image-10-VB7.png
    - assets/page-1/images/image-11-WA5.png
    - assets/page-1/images/image-10-4Bb.png
    - assets/page-1/images/home-VCM.png
    - assets/page-1/images/free-icon-font-home-3917033-2-yTP.png
    - assets/page-1/images/image-14-xZX.png
    - assets/page-1/images/border-7P7.png
    - assets/page-1/images/images-8-sww.png
    - assets/page-1/images/ellipse-7-TDK.png
    - assets/page-1/images/free-icon-font-user-3917546-2-btV.png
    - assets/page-1/images/group-2-6hP.png
    - assets/page-1/images/images-10-LL9.png
    - assets/page-1/images/border-sPw.png
    - assets/page-1/images/free-icon-font-sign-out-alt-1-FfP.png
    - assets/page-1/images/free-icon-font-home-3917033-4-LR7.png
    - assets/page-1/images/account-nRX.png
    - assets/page-1/images/border-MDj.png
    - assets/page-1/images/bg.png
    - assets/page-1/images/group-1-tzM.png
    - assets/page-1/images/free-icon-font-sign-out-alt-1-3pd.png
    - assets/page-1/images/button.png
    - assets/page-1/images/home-8yX.png
    - assets/page-1/images/ellipse-6-bWy.png
    - assets/page-1/images/icon-ETT.png
    - assets/page-1/images/home-mTP.png
    - assets/page-1/images/home-HwX.png
    - assets/page-1/images/free-icon-font-user-3917546-4-529.png
    - assets/page-1/images/location-1Rb.png
    - assets/page-1/images/group-3.png
    - assets/page-1/images/image-10-3U5.png
    - assets/page-1/images/location-HuB.png
    - assets/page-1/images/image-10-pGh.png
    - assets/page-1/images/account-xth.png
    - assets/page-1/images/arrow-down.png
    - assets/page-1/images/image-bg.png
    - assets/page-1/images/image-12.png
    - assets/page-1/images/image-14-gtR.png
    - assets/page-1/images/image-bg-hrR.png
    - assets/page-1/images/image-14-z6M.png
    - assets/page-1/images/image-10-hWZ.png
    - assets/page-1/images/image-10-2z5.png
    - assets/page-1/images/image-bg-xem.png
    - assets/page-1/images/image-11-ZEH.png
    - assets/page-1/images/group-2-pg1.png
    - assets/page-1/images/image-11-NhX.png
    - assets/page-1/images/image-10-2HX.png
    - assets/page-1/images/location-AP3.png
    - assets/page-1/images/image-14-htm.png
    - assets/page-1/images/image-14-nam.png
    - assets/page-1/images/image-12-Gph.png
    - assets/page-1/images/image-10-UDw.png
    - assets/page-1/images/image-10-RQ5.png
    - assets/page-1/images/image-10-yr9.png
    - assets/page-1/images/group-1-Xcm.png
    - assets/page-1/images/image-13.png
    - assets/page-1/images/group-2-idw.png
    - assets/page-1/images/image-10-qGd.png
    - assets/page-1/images/home-nhf.png
    - assets/page-1/images/account-waZ.png
    - assets/page-1/images/account-6iM.png
    - assets/page-1/images/image-10-PjP.png
    - assets/page-1/images/home-Kyb.png
    - assets/page-1/images/image-14-Q5F.png
    - assets/page-1/images/location-xhP.png
    - assets/page-1/images/account-g1X.png
    - assets/page-1/images/home-m5T.png
    - assets/page-1/images/group-2-GiM.png
    - assets/page-1/images/image-13-CBB.png
    - assets/page-1/images/home-xaD.png
    - assets/page-1/images/account-7Y5.png
    - assets/page-1/images/chevron-left.png
    - assets/page-1/images/group-1-eT3.png
    - assets/page-1/images/image-bg-DqK.png
    - assets/page-1/images/image-bg-w2Z.png
    - assets/page-1/images/link.png
    - assets/page-1/images/image-36.png
    - assets/page-1/images/location-ep9.png
    - assets/page-1/images/image-bg-Cfb.png
    - assets/page-1/images/home-bxd.png
    - assets/page-1/images/pie-chart.png
    - assets/page-1/images/group-1-wBP.png
    - assets/page-1/images/image-24.png
    - assets/page-1/images/image-bg-tYH.png
    - assets/page-1/images/actions.png
    - assets/page-1/images/image-bg-qER.png
    - assets/page-1/images/image-bg-LXj.png
    - assets/page-1/images/link-MuK.png
    - assets/page-1/images/group-2-Be1.png
    - assets/page-1/images/account-ouj.png
    - assets/page-1/images/location-YFb.png
    - assets/page-1/images/image-bg-QYy.png
    - assets/page-1/images/image-bg-41F.png
    - assets/page-1/images/location-3RK.png
    - assets/page-1/images/image-bg-bv1.png
    - assets/page-1/images/home-Z6q.png
    - assets/page-1/images/image-bg-FZB.png
    - assets/page-1/images/image-bg-CiM.png
    - assets/page-1/images/nav-icon.png
    - assets/page-1/images/location-eN5.png
    - assets/page-1/images/image-bg-MfX.png
    - assets/page-1/images/image-bg-deq.png
    - assets/page-1/images/image-bg-1SH.png
    - assets/page-1/images/image-32.png
    - assets/page-1/images/image-33.png
    - assets/page-1/images/image-30.png
    - assets/page-1/images/image-31.png
    - assets/page-1/images/image-29.png
    - assets/page-1/images/image-35.png
    - assets/page-1/images/image-34.png
    - assets/page-1/images/image-bg-Lr5.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
